# Paths aconfmgr must never record. Two reasons to be here:
#  - state, caches or generated files that are not configuration
#  - secrets: this repo is public, so anything holding a password, hash or
#    private key is ignored and recreated by hand (docs/manual-steps.md)

# ── secrets ─────────────────────────────────────────────────────────────
IgnorePath '/etc/shadow'
IgnorePath '/etc/shadow-'
IgnorePath '/etc/gshadow'
IgnorePath '/etc/gshadow-'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/NetworkManager/system-connections/*'   # Wi-Fi passwords
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/credstore*'
IgnorePath '/etc/machine-id'                             # unique per install

# Users and groups are created by packages and by useradd in install/, not
# copied around as files (the copies would carry uids and hashes along).
IgnorePath '/etc/passwd'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/group'
IgnorePath '/etc/group-'
IgnorePath '/etc/subuid*'
IgnorePath '/etc/subgid*'

# ── data and state, not configuration ───────────────────────────────────
IgnorePath '/home/*'                # chezmoi's side
IgnorePath '/root/*'
IgnorePath '/mnt/*'                 # C: and anything mounted by hand
IgnorePath '/.snapshots'            # snapper
IgnorePath '/.snapshots/*'
IgnorePath '/var/lib/*'
IgnorePath '/var/cache/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/spool/*'
IgnorePath '/var/db/*'
IgnorePath '/var/.updated'
IgnorePath '/etc/.updated'
IgnorePath '/lost+found'
IgnorePath '/swap*'

# /boot is the ESP: kernels, initramfs and limine.conf are generated by
# limine-entry-tool from /etc/default/limine and /etc/kernel/cmdline (tracked),
# and Windows' boot files live there too. The hand-written parts of
# limine.conf are created by install/.
IgnorePath '/boot/*'

# ── generated by package hooks ──────────────────────────────────────────
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/pacman.d/mirrorlist'          # reflector rewrites it
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/udev/hwdb.bin'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/resolv.conf'
IgnorePath '/etc/xml/catalog'
IgnorePath '/etc/fonts/conf.d/*'
IgnorePath '/etc/os-release'
IgnorePath '/usr/lib/modules/*/updates/*'      # DKMS-built NVIDIA modules
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/lib/gtk-*/*/immodules.cache'
IgnorePath '/usr/lib/graphviz/config*'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/share/icons/*/icon-theme.cache'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/fonts/*/fonts.dir'
IgnorePath '/usr/share/fonts/*/fonts.scale'
IgnorePath '/usr/share/fonts/*/.uuid'
IgnorePath '/usr/share/fonts/.uuid'
IgnorePath '/usr/lib/python3*/site-packages/*/__pycache__'
IgnorePath '/usr/lib/gconv/gconv-modules.cache'
IgnorePath '/usr/lib32/gconv/gconv-modules.cache'
IgnorePath '/usr/lib/modules/*/modules.*'      # depmod output
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/lib/vlc/plugins/plugins.dat'
IgnorePath '/usr/lib/libvsscript.so'           # vapoursynth install hook
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/audisp'
IgnorePath '/etc/audit/*'
IgnorePath '/boot'                             # mode comes from the ESP mount options
IgnorePath '/usr/lib/utempter/utempter'        # mode set by libutempter's install script
IgnorePath '/etc/shells'                       # edited by shell packages' hooks
IgnorePath '/etc/mkinitcpio.d/linux.preset'    # generated by mkinitcpio
IgnorePath '/etc/conf.d/snapper'               # written by `snapper create-config`

# Unit links that package installs create through systemd presets; a fresh
# install recreates them the same way. Units enabled on purpose are in system/*.sh.
IgnorePath '/etc/systemd/system/autovt@.service'
IgnorePath '/etc/systemd/system/getty.target.wants/getty@tty1.service'
IgnorePath '/etc/systemd/system/multi-user.target.wants/remote-fs.target'
IgnorePath '/etc/systemd/system/sockets.target.wants/systemd-userdbd.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/p11-kit-server.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/pipewire.socket'
IgnorePath '/etc/systemd/user/sockets.target.wants/pipewire-pulse.socket'
IgnorePath '/etc/systemd/user/pipewire-session-manager.service'
IgnorePath '/etc/systemd/user/pipewire.service.wants/wireplumber.service'
IgnorePath '/etc/systemd/user/graphical-session-pre.target.wants/xdg-user-dirs.service'
